In [1]:
import numpy as np
import pandas as pd
import librosa
import sklearn
import os
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# names = []
# Letter_names = ["M", "S", "B", "Y"]
# for letter in Letter_names:
#     for index in range(15):
#         names.append({'file':"{0}_open_({1}).wav".format(letter, index), 'label':"{0}".format(letter)})
# file_name = pd.DataFrame(names)
# print(file_name)

In [3]:
Names = os.listdir("AllRecords//Others")
Others_Names_df = pd.DataFrame(Names, columns={'Paths'})
Others_Names_df.insert(1, "Labels", len(Names) *[0])
print(Others_Names_df)

                        Paths  Labels
0    AuphonicRecording_16.wav       0
1    AuphonicRecording_17.wav       0
2    AuphonicRecording_18.wav       0
3    AuphonicRecording_19.wav       0
4    AuphonicRecording_20.wav       0
..                        ...     ...
169            r_open_(5).wav       0
170            r_open_(6).wav       0
171            r_open_(7).wav       0
172            r_open_(8).wav       0
173            r_open_(9).wav       0

[174 rows x 2 columns]


In [4]:
#Getting Team information
team_members = ['Mahmoud Hamdy','Sherif', 'yassmen']
iterator = 0
Team_df = pd.DataFrame()
labels = pd.DataFrame()
for member in team_members:
    iterator += 1
    Team = os.listdir("AllRecords/Team/{0}/Open_the_door".format(member))
    Team_df = Team_df.append(Team,ignore_index=True)
    #Team_df.insert(1, "Label", [iterator]*len(Team))
    labels = labels.append([iterator]*len(Team),ignore_index=True)
# Team_df.insert(1, "Label", labels)
# Data = {
#     "Paths": names,
#     "Labels": labels
# }
# Team_df = pd.DataFrame(Data)
labels = labels.rename(columns={0:"Labels"})
Team_df = Team_df.rename(columns={0:"Paths"})
# print(labels)
# print(Team_df)
Team_df = pd.concat([Team_df,labels], axis=1)
# print(Team_df)
all = Team_df.append(Others_Names_df, ignore_index=True)
print(all)

                          Paths  Labels
0    Mahmoud Recording (10).wav       1
1    Mahmoud Recording (11).wav       1
2    Mahmoud Recording (12).wav       1
3    Mahmoud Recording (13).wav       1
4    Mahmoud Recording (14).wav       1
..                          ...     ...
217              r_open_(5).wav       0
218              r_open_(6).wav       0
219              r_open_(7).wav       0
220              r_open_(8).wav       0
221              r_open_(9).wav       0

[222 rows x 2 columns]


C:\Users\mahmo\AppData\Local\Temp\ipykernel_6696\886542709.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Team_df = Team_df.append(Team,ignore_index=True)
C:\Users\mahmo\AppData\Local\Temp\ipykernel_6696\886542709.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  labels = labels.append([iterator]*len(Team),ignore_index=True)
C:\Users\mahmo\AppData\Local\Temp\ipykernel_6696\886542709.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all = Team_df.append(Others_Names_df, ignore_index=True)


In [5]:
def Extract_features(paths, whichone, dowhat = ''):
    # print(paths)
    # path = os.listdir("AllRecords/{0}/{1}/{2}".format(whichone, dowhat, paths["Paths"]))
    # try:
    path = os.path.join(os.path.abspath('AllRecords/{0}').format(whichone)+ ('\\') +str(paths['Paths']))
    X, sample_rate = librosa.load(path, res_type = "kaiser_fast")
    # except:
    #     print(paths["Paths"])   Voices_frequencies
    # print(path)
    # mfccs = np.mean(librosa.feature.mfcc(Voices_frequencies, sample_rate, n_mfcc = 40).T, axis = 0)
    # mel = np.mean(librosa.feature.melspectrogram(Voices_frequencies, sample_rate).T, axis = 0)
    # tonnetz = np.mean(librosa.feature.tonnetz(librosa.effects.harmonic(Voices_frequencies), sample_rate).T, axis = 0)
    # frequencies_in_stft = np.abs(librosa.stft(Voices_frequencies))
    # chroma = np.mean(librosa.feature.chroma_stft(frequencies_in_stft, sample_rate).T, axis = 0)
    # contrast = np.mean(librosa.feature.spectral_contrast(frequencies_in_stft, sample_rate).T, axis = 0)
    # label = paths['Labels']
    # return mfccs, mel, tonnetz, chroma, contrast, label
    # Generate Mel-frequency cepstral coefficients (MFCCs) from a time series 
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)

    # Generates a Short-time Fourier transform (STFT) to use in the chroma_stft
    stft = np.abs(librosa.stft(X))

    # Computes a chromagram from a waveform or power spectrogram.
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)

    # Computes a mel-scaled spectrogram.
    mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)

    # Computes spectral contrast
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)

    # Computes the tonal centroid features (tonnetz)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),
    sr=sample_rate).T,axis=0)
        
    
    # We add also the classes of each file as a label at the end
    return [mfccs, chroma, mel, contrast, tonnetz]
# def extract_features(files):
    
#     # Sets the name to be the path to where the file is in my computer
#     file_name = os.path.join(os.path.abspath('all')+'/'+str(files.file))

#     # Loads the audio file as a floating point time series and assigns the default sample rate
#     # Sample rate is set to 22050 by default
#     X, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 

#     # Generate Mel-frequency cepstral coefficients (MFCCs) from a time series 
#     mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)

#     # Generates a Short-time Fourier transform (STFT) to use in the chroma_stft
#     stft = np.abs(librosa.stft(X))

#     # Computes a chromagram from a waveform or power spectrogram.
#     chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)

#     # Computes a mel-scaled spectrogram.
#     mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)

#     # Computes spectral contrast
#     contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)

#     # Computes the tonal centroid features (tonnetz)
#     tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),
#     sr=sample_rate).T,axis=0)
        
    
#     # We add also the classes of each file as a label at the end
#     label = files.label

#     return mfccs, chroma, mel, contrast, tonnetz, label


In [6]:
mfccs = []
mel = []
tonnetz = []
chroma = []
contrast = []
label_enter = []
DataSet = pd.DataFrame()
# print(Team_df['Paths'])
DataSet = all.apply(Extract_features, whichone="AllTeams", axis=1)
# for i in range(len(Team_df)):
#     vmfcc, vmel, vtonnetz, vchroma, vcontrast, vlabel = Extract_features(Team_df[i], "Team", "Open_the_door")
#     mel.append(vmel)
#     tonnetz.append(vtonnetz)
#     chroma.append(vchroma)
#     contrast.append(vcontrast)
#     label_enter.append(vlabel)
#     mfccs.append(vmfcc)
# Data = {
#     "mfccs": mfccs,
#     "mel": mel,
#     "chroma": chroma,
#     "tonnetz": tonnetz,
#     "contrast": contrast,
#     "Labels": label_enter
# }
# DataSet = pd.DataFrame(Data)
dd = np.array(DataSet[0])
print(dd.shape)

c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=672
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=662
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=659
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=693
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=762
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=700
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length

(5,)


C:\Users\mahmo\AppData\Local\Temp\ipykernel_6696\3263792091.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  dd = np.array(DataSet[0])


In [7]:
print(DataSet[0])

[array([-5.6601459e+02,  1.3559920e+02, -3.2716188e+00,  1.4285082e+01,
        4.3028116e+00, -2.6343584e+00,  5.9902267e+00, -2.0260577e+00,
       -1.0903160e+01,  9.2623796e+00, -2.1448741e+00,  2.0591328e+00,
        6.2542090e+00, -6.5690720e-01,  6.7364612e+00,  2.0906706e+00,
       -1.1721684e+01, -1.9925401e+00, -6.0295572e+00, -8.7338543e+00,
       -1.8281145e+00, -4.9330029e+00, -8.7488251e+00, -1.1285790e+00,
       -3.0232403e+00, -2.9712000e+00, -4.3046651e+00, -3.7989037e+00,
       -6.3605738e-01, -2.9513237e+00, -5.5968219e-01, -7.2163951e-01,
       -2.8727169e+00, -1.9239919e+00,  3.5328960e-01, -1.0242617e+00,
        4.6082778e+00,  4.6122227e+00,  1.2963264e+00,  1.6458834e+00],
      dtype=float32), array([0.55790514, 0.60550046, 0.5673392 , 0.54633534, 0.527548  ,
       0.49981943, 0.55150086, 0.49659693, 0.49646065, 0.5933563 ,
       0.58242714, 0.52085984], dtype=float32), array([1.8044002e-03, 1.5289659e-03, 8.9376338e-04, 2.7220080e-02,
       2.5833210e

In [8]:
def features_append(features):
    feature = []
    for i in range(len(features)):
        feature.append(np.concatenate((features[i][0], features[i][1], features[i][2]
        , features[i][3],features[i][4])))
    return feature


In [9]:
x = features_append(DataSet)
# df = pd.DataFrame(x)
# print(df)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x, all['Labels'], test_size=0.2, random_state=0)

In [11]:
clf = RandomForestClassifier(random_state=0, n_estimators=40)
clf.fit(X_train,y_train.values.ravel())

RandomForestClassifier(n_estimators=40, random_state=0)

In [12]:
y_pred = clf.predict(X_test)

In [13]:
clf.predict(X_test)

array([0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0], dtype=int64)

In [14]:
y_test

130    0
203    0
170    0
66     0
181    0
141    0
44     3
71     0
64     0
8      1
83     0
37     3
5      1
199    0
63     0
166    0
106    0
204    0
202    0
89     0
109    0
191    0
124    0
74     0
76     0
12     1
157    0
159    0
123    0
144    0
55     0
122    0
97     0
104    0
18     1
15     1
188    0
7      1
75     0
161    0
96     0
149    0
90     0
176    0
143    0
Name: Labels, dtype: int64

In [15]:
a = accuracy_score(y_pred, y_test)
print(a)

0.9777777777777777


In [16]:
clf.predict(x[:12])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [17]:
all['Labels'][:12]

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
Name: Labels, dtype: int64

In [18]:
newTest = os.listdir("AllRecords/Test/")
Test = pd.DataFrame(newTest, columns={"Paths"})
get_feat = Test.apply(Extract_features, whichone='Test', axis=1)
combine = features_append(get_feat)

c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=684
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=631
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=569
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=700
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=827
  warnings.warn(
c:\Python310\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=1024 is too small for input signal of length=634
  warnings.warn(


In [19]:
clf.predict(combine)

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 2, 3], dtype=int64)